[tool.poetry]
name = "dangerzone"
version = "0.1.4"
description = "Take potentially dangerous PDFs, office documents, or images and convert them to a safe PDF"
authors = ["Micah Lee <micah.lee@theintercept.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
click = "*"
appdirs = "*"
requests = "*"
macholib = "*"
termcolor = "*"
PySide2 = "^5.15.1"
pywin32 = {version = "*", platform = "win32"}
wmi = {version = "*", platform = "win32"}
pyxdg = {version = "*", platform = "linux"}
pyobjc-core = {version = "*", platform = "darwin"}
pyobjc-framework-launchservices = {version = "*", platform = "darwin"}

[tool.poetry.dev-dependencies]
pyinstaller = {version = "*", platform = "darwin"}
setuptools = {version = "*", platform = "win32"}

[tool.poetry.scripts]
dangerzone = 'dangerzone:main'
dangerzone-container = 'dangerzone:main'

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
